# Generated by Django 3.2.6 on 2022-04-19 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuestionarioNom035', '0002_alter_categoria_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dominio', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuestionarioNom035.categoria')),
            ],
        ),
    ]
