# Generated by Django 3.2.6 on 2022-04-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuestionarioNom035', '0003_dominio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominio',
            name='dominio',
            field=models.CharField(max_length=100),
        ),
    ]
