# Generated by Django 3.2.6 on 2022-04-19 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuestionarioNom035', '0005_dimension_reactivo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dimension',
            new_name='Dimensiones',
        ),
    ]
