# Generated by Django 3.2.6 on 2022-04-19 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuestionarioNom035', '0006_rename_dimension_dimensiones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dimensiones',
            new_name='Dimension',
        ),
    ]
