# Generated by Django 3.2.6 on 2022-04-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuestionarioNom035', '0008_remove_reactivo_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuestionario', models.CharField(max_length=100)),
                ('preguntas', models.ManyToManyField(to='CuestionarioNom035.Reactivo')),
            ],
        ),
    ]
