# Generated by Django 3.2.6 on 2022-04-20 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuestionarioNom035', '0011_auto_20220419_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuestionario',
            name='preguntas',
        ),
        migrations.RemoveField(
            model_name='cuestionario',
            name='valor',
        ),
        migrations.AddField(
            model_name='reactivo',
            name='cuestionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CuestionarioNom035.cuestionario'),
            preserve_default=False,
        ),
    ]
