# Generated by Django 3.2.6 on 2022-04-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuestionarioNom035', '0012_auto_20220419_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactivo',
            name='valor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
