# Generated by Django 3.2.6 on 2022-04-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuestionarioNom035', '0014_remove_reactivo_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactivo',
            name='cuestionario',
        ),
        migrations.RemoveField(
            model_name='reactivo',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='cuestionario',
        ),
        migrations.DeleteModel(
            name='Cuestionario',
        ),
        migrations.DeleteModel(
            name='Reactivo',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
