# Generated by Django 3.2.6 on 2022-04-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuestionarioNom035', '0015_auto_20220420_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuestionario', models.CharField(max_length=100)),
            ],
        ),
    ]
