# Generated by Django 3.2.6 on 2022-04-20 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuestionarioNom035', '0016_cuestionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reactivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('pregunta', models.CharField(max_length=100)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuestionarioNom035.dimension')),
            ],
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='preguntas',
            field=models.ManyToManyField(to='CuestionarioNom035.Reactivo'),
        ),
    ]
