# Generated by Django 3.2.6 on 2022-04-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuestionarioNom035', '0018_respuestacuestionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuestPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuestionario', models.ManyToManyField(to='CuestionarioNom035.Reactivo')),
            ],
        ),
        migrations.RemoveField(
            model_name='cuestionario',
            name='preguntas',
        ),
        migrations.DeleteModel(
            name='RespuestaCuestionario',
        ),
        migrations.AddField(
            model_name='cuestpregunta',
            name='reactivo',
            field=models.ManyToManyField(to='CuestionarioNom035.Cuestionario'),
        ),
    ]
