# Generated by Django 3.2.6 on 2022-04-20 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuestionarioNom035', '0021_auto_20220420_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuestpregunta',
            name='cuestionario',
        ),
        migrations.AddField(
            model_name='cuestpregunta',
            name='cuestionario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CuestionarioNom035.cuestionario'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cuestpregunta',
            name='reactivo',
        ),
        migrations.AddField(
            model_name='cuestpregunta',
            name='reactivo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CuestionarioNom035.reactivo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RespuestaCuestionario',
        ),
    ]
