# Generated by Django 3.2.6 on 2022-04-20 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CuestionarioNom035', '0024_respcuestpregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='respcuestpregunta',
            name='pregunta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CuestionarioNom035.cuestpregunta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respcuestpregunta',
            name='cuestionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuestionarioNom035.cuestionario'),
        ),
    ]
