# Generated by Django 3.2.6 on 2022-04-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuestionarioNom035', '0027_cuestionario72'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario72',
            name='p65',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionario72',
            name='p66',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionario72',
            name='p67',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionario72',
            name='p68',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionario72',
            name='p69',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionario72',
            name='p70',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionario72',
            name='p71',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionario72',
            name='p72',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
